mingkang/docs/add doc for oci data science
raveharpaz/langchain pull request #1
Opened 2024-02-06 22:08 UTC by mingkang111

# Description

Add introduction page for OCI Data Science platform in LangChain's documentation.

2024-02-07 01:07 UTC, raveharpaz requested changes

2024-02-07 01:07 UTC, raveharpaz commented on docs/docs/integrations/platforms/oci.mdx
> +classes to interact with it.
we recommend removing this and follow the content/detail level supplied by other providers. This page is meant to serve as a landing page with links to more detailed information about integrations in the specific docs. Maybe we can change a bit to combine the 1st and 2nd paragraphs: "OCI Data Science is a fully managed and serverless platform for data science teams. Using the OCI Data Science platform you can build, train, manage machine learning models, and then deploy them as OCI Model Deployment Endpoint using the OCI Data Science Model Deployment Service."

2024-02-07 01:07 UTC, YouNeedCryDear requested changes

2024-02-07 01:07 UTC, YouNeedCryDear commented on docs/docs/integrations/platforms/oci.mdx
> +pip install - U oracle-ads
There should be no space between - and U

2024-02-09 21:48 UTC, raveharpaz approved these changes

2024-02-09 21:53 UTC, merged

2024-02-09 21:54 UTC, raveharpaz commented
new ADS docs (2x files oci.mdx,  docs/integrations/platforms /index.mdx)